import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    fetch("http://localhost:8000/create-user", { method: "GET" });

    console.log(fetch("http://localhost:8000/users", { method: "GET" }));
  })

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
